version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
  open-pull-requests-limit: 10
