changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Exciting New Features
      labels:
        - new-features
    - title: Refactor
      labels:
        - refactor
    - title: Bugfixes
      labels:
        - bugfix
    - title: Dependency changes\n_test_
      labels:
        - dependencies
    - title: Internal
      labels:
        - internal
